#!/usr/bin/env bash
# The script displays username. user id, and home directory path for the user
FILENAME="/etc/passwd"


while read LINE
do
	    echo "$LINE" | cut -d ":" -f1,3,6
    done < "$FILE"
