#!/bin/bash
# The script displays username. user id, and home directory path for the user
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
    echo "$username, $userid, $comment $homedir"
done < $FILENAM
